#!/bin/sh
#
# @name Gazebo x500 Custom
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_custom_2}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=custom}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default SYS_HAS_GPS 0
param set-default SIM_GPS_USED 0
param set-default EKF2_GPS_CTRL 0

param set-default NAV_DLL_ACT 0